version: "3"

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - '8080:8080'
    links:
      - db

volumes:
  db:
    driver: local
