version: "3"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8888:8080"
    restart: unless-stopped

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5773:5173"
    restart: unless-stopped
    depends_on:
      - backend
