CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(30)                             NOT NULL UNIQUE,
    password VARCHAR                                 NOT NULL
);
